---

- name: create the nginx_exporter systemd service file
  ansible.builtin.template:
    src: init/systemd/nginx_exporter.service.j2
    dest: "{{ systemd_lib_directory }}/nginx_exporter.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload

- name: create nginx_exporter config
  ansible.builtin.template:
    src: nginx_exporter.j2
    dest: "{{ sysconfig_directory }}/nginx_exporter"
    mode: 0644
  notify:
    - restart nginx_exporter

...
