---

- name: This repository will therefore no longer be actively maintained.
  ansible.builtin.fail:
    msg: |
      Further development of this Ansible role has been moved to Collection bodsch.prometheus.
      This repository will therefore no longer be actively maintained.
  ignore_errors: true

- name: wait 10 seconds to realise the message
  delegate_to: localhost
  ansible.builtin.wait_for:
    timeout: 10

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    nginx_exporter_delegate_to: "{{ ansible_host }}"
    nginx_exporter_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/nginx_exporter', true) }}/{{ nginx_exporter_version }}"
  when:
    - nginx_exporter_direct_download

- name: install dependency
  ansible.builtin.package:
    name: "{{ nginx_exporter_requirements }}"
    state: present
  when:
    - nginx_exporter_requirements | default([]) | count > 0

- name: latest version
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - nginx_exporter_version == "latest"
  block:
    - name: get latest release
      ansible.builtin.uri:
        url: "https://api.github.com/repos/nginxinc/nginx-prometheus-exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        validate_certs: false
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      # no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: set nginx_exporter version to {{ _latest_release.json.tag_name[1:] }}
      ansible.builtin.set_fact:
        nginx_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"

- name: detect our installation path '{{ nginx_exporter_install_path | dirname }}'
  ansible.builtin.stat:
    path: "{{ nginx_exporter_install_path | dirname }}"
    get_checksum: false
  register: stat_nginx_exporter_path
  ignore_errors: true

- name: old installation
  when:
    - stat_nginx_exporter_path is defined
    - stat_nginx_exporter_path.stat is defined
    - stat_nginx_exporter_path.stat.isdir is defined
    - not stat_nginx_exporter_path.stat.isdir
  block:
    - name: stop old service
      ansible.builtin.service:
        name: nginx_exporter
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/nginx_exporter.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed nginx_exporter
      ansible.builtin.file:
        state: absent
        path: "{{ stat_nginx_exporter_path.stat.path }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: detect installed nginx_exporter binary
  ansible.builtin.stat:
    path: "{{ nginx_exporter_install_path }}/nginx_exporter"
  register: stat_nginx_exporter_binary

- name: create download directory
  become: false
  delegate_to: "{{ nginx_exporter_delegate_to }}"
  run_once: "{{ 'false' if nginx_exporter_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ nginx_exporter_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: user and group handling
  when:
    - nginx_exporter_system_user != "root"
  block:
    - name: create nginx_exporter group
      ansible.builtin.group:
        name: "{{ nginx_exporter_system_group }}"
        state: present
        system: true

    - name: create nginx_exporter user
      ansible.builtin.user:
        name: "{{ nginx_exporter_system_user }}"
        groups: "{{ nginx_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ nginx_exporter_install_path }}"
    state: directory
    owner: "{{ nginx_exporter_system_user }}"
    group: "{{ nginx_exporter_system_group }}"
    mode: 0755

- name: fix directory rights for {{ nginx_exporter_install_path | dirname }}
  ansible.builtin.file:
    path: "{{ nginx_exporter_install_path | dirname }}"
    state: directory
    owner: "{{ nginx_exporter_system_user }}"
    group: "{{ nginx_exporter_system_group }}"
    mode: 0755
    recurse: true

- name: create ansible local facts directory
  ansible.builtin.file:
    dest: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0775

- name: merge nginx_exporter configuration between defaults and custom
  ansible.builtin.set_fact:
    nginx_exporter_config: "{{ nginx_exporter_defaults_config | combine(nginx_exporter_config, recursive=True) }}"

...
