---

nginx_vhosts:
  # HTTP
  # ssl: false
  # LE: false
  default:
    # Set to True if you want to redirect http to https
    ssl:
      enabled: false

  nginx-status:
    filename: 00-status.conf
    state: present  # default: present
    enabled: true   # default: true
    # domain(s)
    domains:
      - localhost
    # listen
    listen:
      - 127.0.0.1:8088
    # locations
    locations:
      "/nginx_status":
        options: |
          stub_status on;
          access_log off;
          allow 127.0.0.1;
          deny all;

...
